# Generated by Django 5.2.11 on 2026-02-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="currency_preference",
            field=models.CharField(
                default="KES", help_text="ISO 4217 currency code", max_length=3
            ),
        ),
    ]
